env:
  browser: true
  es2021: true
extends:
  - google
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  no-unused-vars: "off"
  "@typescript-eslint/no-unused-vars": [
    "error",
    {
      "argsIgnorePattern": "^_$"
    }
  ]
  new-cap:
    - error
    - capIsNewExceptions:
      - Set
      - Map
ignorePatterns:
  # Generated type files.
  - "*.d.ts"
